name: kleofas2
description: Ultimátní client pro školu
publish_to: 'none'
version: 1.0.0+1

environment:
  # sdk: '>=2.19.0 <3.0.0'
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  result_type: ^0.2.0
  intl: ^0.17.0
  pocketbase: ^0.10.1
  workmanager: ^0.5.1
  html_unescape: ^2.0.0
  universal_html: ^2.2.1
  file_picker: ^5.3.0
  flutter_local_notifications: ^14.1.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  flutter_colorpicker: ^1.0.3
  mobile_scanner: ^3.4.1
  image_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.jpg"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Discord
  #     fonts:
  #       - asset: assets/ggsans-Normal.ttf
  #       - asset: assets/ggsans-Bold.ttf
  #         weight: 500
  #       - asset: assets/ggsans-NormalItalic.ttf
  #         style: italic
  #       - asset: assets/ggsans-BoldItalic.ttf
  #         weight: 500
  #         style: italic